language: python
jobs:
  include:
    - name: "linux"
      sudo: false
      python:
        - 3.5
        - 3.6
        - 3.7
    - name: "windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - pip install pytest
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest -v